In [1]:
import pandas as pd

In [2]:
# 2 main Data types in Pandas 
# 1. Series     : 1 Dimensional
# 2. Dataframe  : 2 Dimensional

series = pd.Series(["Apple","Banana","Orange"])
print(series)

0     Apple
1    Banana
2    Orange
dtype: str

In [3]:
df = pd.DataFrame({
    "fruits" : ["Apple","Banana","Mango","Orange"],
    "colors" : ["Red","Yellow","Yellow","Orange"]
})

df

   fruits  colors
0   Apple     Red
1  Banana  Yellow
2   Mango  Yellow
3  Orange  Orange

In [4]:
car_sales = pd.read_csv('car-sales.csv')
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [5]:
# Exporting a dataset 
car_sales.to_csv("car-sales-exported.csv",index=False)

## Describing Data In Pandas

In [6]:
car_sales.dtypes

Make               str
Colour             str
Odometer (KM)    int64
Doors            int64
Price              str
dtype: object

In [7]:
car_sales.columns

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='str')

In [8]:
car_sales.index

RangeIndex(start=0, stop=10, step=1)

In [9]:
car_sales.describe()

       Odometer (KM)      Doors
count      10.000000  10.000000
mean    78601.400000   4.000000
std     61983.471735   0.471405
min     11179.000000   3.000000
25%     35836.250000   4.000000
50%     57369.000000   4.000000
75%     96384.500000   4.000000
max    213095.000000   5.000000

In [10]:
car_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     str
 1   Colour         10 non-null     str
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     str
dtypes: int64(2), str(3)
memory usage: 532.0 bytes

In [11]:
car_sales.mean(numeric_only=True)

Odometer (KM)    78601.4
Doors                4.0
dtype: float64

In [12]:
car_sales["Doors"].sum()

np.int64(40)

In [13]:
len(car_sales)

10

## Viewing and Selecting Data

In [14]:
car_sales.head(4)

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00

In [15]:
car_sales.tail(4)

     Make Colour  Odometer (KM)  Doors      Price
6   Honda   Blue          45698      4  $7,500.00
7   Honda   Blue          54738      4  $7,000.00
8  Toyota  White          60000      4  $6,250.00
9  Nissan  White          31600      4  $9,700.00

In [16]:
series = pd.Series(["Red","Blue","Green","Yello","Orange"],
                   index=[3,4,2,4,6])
series

3       Red
4      Blue
2     Green
4     Yello
6    Orange
dtype: str

In [17]:
series.loc[4]

4     Blue
4    Yello
dtype: str

In [18]:
series.iloc[4]

'Orange'

In pandas, the core difference is that .loc is label-based (uses names to select data) while .iloc is integer position-based (uses numeric 0-indexed positions).

In [19]:
car_sales.head()

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [20]:
car_sales.loc[4]

Make                Nissan
Colour               White
Odometer (KM)       213095
Doors                    4
Price            $3,500.00
Name: 4, dtype: object

In [21]:
car_sales.iloc[4]

Make                Nissan
Colour               White
Odometer (KM)       213095
Doors                    4
Price            $3,500.00
Name: 4, dtype: object

In [22]:
car_sales.iloc[:4]

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00

In [23]:
car_sales.loc[:3]

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00

In [24]:
car_sales[car_sales["Make"]=="Toyota"]

     Make Colour  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
2  Toyota   Blue          32549      3  $7,000.00
5  Toyota  Green          99213      4  $4,500.00
8  Toyota  White          60000      4  $6,250.00

In [25]:
pd.crosstab(car_sales["Make"],car_sales["Doors"])

Doors   3  4  5
Make
BMW     0  0  1
Honda   0  3  0
Nissan  0  2  0
Toyota  1  3  0

In [29]:
car_sales.groupby("Make")["Doors"].mean()

Make
BMW       5.00
Honda     4.00
Nissan    4.00
Toyota    3.75
Name: Doors, dtype: float64

In [30]:
car_sales

     Make Colour  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

In [31]:
car_sales["Price"] = car_sales["Price"].str.replace(r'[\$\,]', '', regex=True).astype(float)

In [32]:
car_sales

     Make Colour  Odometer (KM)  Doors    Price
0  Toyota  White         150043      4   4000.0
1   Honda    Red          87899      4   5000.0
2  Toyota   Blue          32549      3   7000.0
3     BMW  Black          11179      5  22000.0
4  Nissan  White         213095      4   3500.0
5  Toyota  Green          99213      4   4500.0
6   Honda   Blue          45698      4   7500.0
7   Honda   Blue          54738      4   7000.0
8  Toyota  White          60000      4   6250.0
9  Nissan  White          31600      4   9700.0

## Manipulating Data

In [33]:
car_sales["Make"].str.lower()

0    toyota
1     honda
2    toyota
3       bmw
4    nissan
5    toyota
6     honda
7     honda
8    toyota
9    nissan
Name: Make, dtype: str

In [34]:
car_sales_missing = pd.read_csv("car-sales-missing-data.csv")
car_sales_missing

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

In [39]:
car_sales_missing["Odometer"] = car_sales_missing["Odometer"].fillna(car_sales_missing["Odometer"].mean(),inplace=True)

C:\Users\Acer\AppData\Local\Temp\ipykernel_20980\3265876450.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  car_sales_missing["Odometer"] = car_sales_missing["Odometer"].fillna(car_sales_missing["Odometer"].mean(),inplace=True)

In [40]:
car_sales_missing

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500
6   Honda    NaN   92302.666667    4.0   $7,500
7   Honda   Blue   92302.666667    4.0      NaN
8  Toyota  White   60000.000000    NaN      NaN
9     NaN  White   31600.000000    4.0   $9,700

In [44]:
car_sales_missing.dropna(inplace=True)

In [45]:
car_sales_missing

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500

In [46]:
car_sales

     Make Colour  Odometer (KM)  Doors    Price
0  Toyota  White         150043      4   4000.0
1   Honda    Red          87899      4   5000.0
2  Toyota   Blue          32549      3   7000.0
3     BMW  Black          11179      5  22000.0
4  Nissan  White         213095      4   3500.0
5  Toyota  Green          99213      4   4500.0
6   Honda   Blue          45698      4   7500.0
7   Honda   Blue          54738      4   7000.0
8  Toyota  White          60000      4   6250.0
9  Nissan  White          31600      4   9700.0

In [47]:
car_sales["Seats"] =  5

In [48]:
car_sales

     Make Colour  Odometer (KM)  Doors    Price  Seats
0  Toyota  White         150043      4   4000.0      5
1   Honda    Red          87899      4   5000.0      5
2  Toyota   Blue          32549      3   7000.0      5
3     BMW  Black          11179      5  22000.0      5
4  Nissan  White         213095      4   3500.0      5
5  Toyota  Green          99213      4   4500.0      5
6   Honda   Blue          45698      4   7500.0      5
7   Honda   Blue          54738      4   7000.0      5
8  Toyota  White          60000      4   6250.0      5
9  Nissan  White          31600      4   9700.0      5

In [49]:
car_sales.sample(frac=1)

     Make Colour  Odometer (KM)  Doors    Price  Seats
4  Nissan  White         213095      4   3500.0      5
2  Toyota   Blue          32549      3   7000.0      5
3     BMW  Black          11179      5  22000.0      5
1   Honda    Red          87899      4   5000.0      5
7   Honda   Blue          54738      4   7000.0      5
5  Toyota  Green          99213      4   4500.0      5
9  Nissan  White          31600      4   9700.0      5
8  Toyota  White          60000      4   6250.0      5
0  Toyota  White         150043      4   4000.0      5
6   Honda   Blue          45698      4   7500.0      5

In [51]:
data_shuffled = car_sales.sample(frac=0.8)

In [52]:
data_shuffled

     Make Colour  Odometer (KM)  Doors    Price  Seats
1   Honda    Red          87899      4   5000.0      5
8  Toyota  White          60000      4   6250.0      5
3     BMW  Black          11179      5  22000.0      5
2  Toyota   Blue          32549      3   7000.0      5
0  Toyota  White         150043      4   4000.0      5
4  Nissan  White         213095      4   3500.0      5
7   Honda   Blue          54738      4   7000.0      5
9  Nissan  White          31600      4   9700.0      5

In [57]:
data_shuffled.reset_index(inplace=True,drop=True)

In [59]:
data_shuffled.drop(columns=["index"],inplace=True)

In [60]:
data_shuffled

     Make Colour  Odometer (KM)  Doors    Price  Seats
0   Honda    Red          87899      4   5000.0      5
1  Toyota  White          60000      4   6250.0      5
2     BMW  Black          11179      5  22000.0      5
3  Toyota   Blue          32549      3   7000.0      5
4  Toyota  White         150043      4   4000.0      5
5  Nissan  White         213095      4   3500.0      5
6   Honda   Blue          54738      4   7000.0      5
7  Nissan  White          31600      4   9700.0      5

In [61]:
data_shuffled["Seats"] = data_shuffled["Seats"].apply(lambda x : x*2-4)

In [62]:
data_shuffled

     Make Colour  Odometer (KM)  Doors    Price  Seats
0   Honda    Red          87899      4   5000.0      6
1  Toyota  White          60000      4   6250.0      6
2     BMW  Black          11179      5  22000.0      6
3  Toyota   Blue          32549      3   7000.0      6
4  Toyota  White         150043      4   4000.0      6
5  Nissan  White         213095      4   3500.0      6
6   Honda   Blue          54738      4   7000.0      6
7  Nissan  White          31600      4   9700.0      6